version: '3.1'

services:

  db:
    image: pharmacollect/mariadb:v0.0.1
    restart: always
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: dev-pharmacollect
      MYSQL_PASSWORD: BEisen2020
    volumes:
      - /home/ph-admin/PharmaCollect/mariadb_data:/var/lib/mysql
      - /home/ph-admin/PharmaCollect/mariadb_config/ssl:/etc/ssl/mariadb
      - /home/ph-admin/PharmaCollect/mariadb_config/my.cnf:/etc/mysql/my.cnf
    ports:
      - 3306:3306    
  
  node:
    image: pharmacollect/node:latest
    restart: always
    deploy:
      replicas: 1
    depends_on:
      - db
    labels:
      - "traefik.http.routers.node.rule=Host(`node`)"
      - "traefik.http.routers.node-tls.tls.domains[0].main=node.traefik.me"
      - "traefik.http.routers.node-tls.tls.domains[0].sans=node-*.traefik.me"
      - "traefik.http.routers.node.tls=true"
    environment:
     - NODE_ENV=production
    command:  node /usr/src/app/server.js

  
  reverse-proxy:
    restart: unless-stopped
    container_name: rproxy
    image: traefik:v2.3
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8081:8080"
      - "8082:8082"
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./tls.yml:/etc/traefik/tls.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - certs:/etc/ssl/traefik
      - ./logtraefik:/var/log

  reverse-proxy-https-helper:
    image: alpine
    container_name: rproxy_helper
    command: sh -c "cd /etc/ssl/traefik
      && wget traefik.me/cert.pem -O cert.pem
      && wget traefik.me/privkey.pem -O privkey.pem"
    volumes:
      - certs:/etc/ssl/traefik

volumes:
  certs:
    
