version: '3.1'

services:

  db:
    image: pharmacollect/mariadb:v0.0.1
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: dev-pharmacollect
      MYSQL_PASSWORD: BEisen2020
    volumes:
      - /home/ph-admin/PharmaCollect/mariadb_data:/var/lib/mysql
    ports:
      - 3306:3306    
  
  phpmyadmin:
    image: pharmacollect/phpmyadmin:v0.0.1
    restart: always
    ports:
      - 6443:443
    volumes:
      - /home/ph-admin/PharmaCollect/phpmyadmin_data/config.inc.php:/etc/phpmyadmin/config.inc.php
      - /home/ph-admin/PharmaCollect/phpmyadmin_data/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
      - /home/ph-admin/PharmaCollect/phpmyadmin_data/cert:/etc/ssl/phpmyadmin
      - /home/ph-admin/PharmaCollect/phpmyadmin_data/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - /home/ph-admin/PharmaCollect/phpmyadmin_data/log:/var/log/apache2/

